# Generated by Django 5.1.2 on 2024-11-15 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Beca', '0002_verificacion_actividadverificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField(db_column='DueDate')),
                ('descripcion', models.TextField(db_column='Description')),
                ('estado', models.CharField(db_column='Status', default='en progreso', max_length=255)),
                ('puntos', models.IntegerField(db_column='Points')),
                ('actividad', models.ForeignKey(db_column='ActivityID', on_delete=django.db.models.deletion.CASCADE, to='Beca.actividadbeca')),
                ('usuario', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Tasks',
            },
        ),
    ]
