# Generated by Django 5.1.2 on 2024-11-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('location', models.CharField(db_column='Location', max_length=500)),
            ],
            options={
                'db_table': 'Files',
            },
        ),
        migrations.CreateModel(
            name='VerificationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_status', models.CharField(db_column='Status', max_length=255)),
                ('verified_count', models.IntegerField(db_column='Count', default=0)),
                ('total_verifications', models.IntegerField(db_column='VerificationsTotal', default=0)),
            ],
            options={
                'db_table': 'VerificationFile',
            },
        ),
    ]
