# Generated by Django 5.1.2 on 2024-11-15 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Beca', '0002_verificacion_actividadverificacion'),
        ('Files', '0001_initial'),
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='task',
            field=models.ForeignKey(db_column='TaskID', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Tasks.task'),
        ),
        migrations.AddField(
            model_name='verificationfile',
            name='actividad_verificacion',
            field=models.ForeignKey(db_column='ActividadVerificacionID', on_delete=django.db.models.deletion.CASCADE, to='Beca.actividadverificacion'),
        ),
        migrations.AddField(
            model_name='verificationfile',
            name='file',
            field=models.OneToOneField(db_column='FileID', on_delete=django.db.models.deletion.CASCADE, to='Files.file'),
        ),
    ]
