# Generated by Django 5.1.2 on 2024-11-06 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    def cargar_datos (apps, schema_editor):
        Verificacion = apps.get_model('Beca', 'Verificacion')

        verificaciones = [
            {"name": "Nombre", "description": "Nombre del usuario"},
            {"name": "Fecha", "description": "Documento en el intervalo de tiempo acordado"},
            {"name": "Formato Unico de Personal", "description": "Que tenga la cadena de Formato Unico de Personal"},
            {"name": "Resultado", "description": "Resultado impartido"},
            {"name": "Puntuacion dividida", "description": "Los puntos de dividiran entre el numero de participantes"},
            {"name": "Puntuacion PNCP", "description": "Depende si es de PNCP es puntuación total si no es entonces se divide entre los participantes"},
            {"name": "Excluir 1", "description": "Se excluyen con la II.5.1 y II.5.2"},
            {"name": "Excluir 2", "description": "Se excluyen con la II.5.3 y II.5.4"},
            {"name": "Nombramiento", "description": "Nombramiento por parte de la institucion"},
            {"name": "Periodo", "description": "Constancia oficial del periodo desempeñado"},
            {"name": "Excluir 3", "description": "Se excluyen con la II.7.3, II.7.4 y II.7.5"},
            {"name": "Grado obtenido", "description": "Comprobacion del grado obtenido"},
            {"name": "Registro", "description": "Numero de registro"},
            {"name": "Horas", "description": "Cumplimiento de horas del periodo"},
            {"name": "Nivel Ingles", "description": "Constancia de nivel expendida por CELEX"},
            {"name": "Unidad Academica", "description": "Constancia impartida por la DEMS"},
            {"name": "Media Superior o Superior", "description": "Que es ¿Media superior o superior?, nombre del congreso y fecha"},
            {"name": "¿Es posgrado?", "description": "Tipo de participacion en la creacion o actualizacion, los participantes y tipo de participacion"},
            {"name": "Nombre del congreso", "description": "Nombre completo del congreso"},
            {"name": "Participante", "description": "Participante y sus contancia oficial"},
            {"name": "Constancia Unidad academica", "description": "Constancia oficial de la direccion de la unidad academica"},
            {"name": "Nombre del programa academico", "description": "Nombre completo del programa academico"},
            {"name": "Clave del documento", "description": "Clave completa del documento"},
            {"name": "Tipo de material", "description": "Tipos de material como apuntes, manuales, etc."},
            {"name": "Titulo", "description": "Titulo del recurso"},
            {"name": "Autores", "description": "Participantes en la elaboración de los recursos"},
            {"name": "Semestre", "description": "Coicidencia en el semestre del la elaboración del recurso"},
            {"name": "Calificación", "description": "Caificación aprobatoria del 80%"},
            {"name": "Unidad de aprendizaje", "description": "Unidad de aprendizaje del recurso didáctico elaborado"},
            {"name": "Capitulos", "description": "Contribución por capítulo"},
            {"name": "Copia de publicación", "description": "Esta copia debe tener portada, indice y trabajo"},
            {"name": "Participacion 2", "description": "Esta participación debe ser ponente"},
            {"name": "Tipo de distinción", "description": "Si es de IPN o externa ya que serán mas o menos puntos"},
            {"name": "Comisión", "description": "El inicio y termino de esta"},
            {"name": "Comisión evaluadora", "description": "Evaluación inicial o proceso de incorfomidad"},
            {"name": "Titular de la unidad academica", "description": "Nombre del titular que imparte la unidad academica"},
            {"name": "Integrantes", "description": "Nombres de los integrantes en la actividad de comisión"},
            {"name": "Grado maximo", "description": "El grado maximo de estudios"},
            {"name": "Antiguedad", "description": "Antiguedad expendida por el instituto"},
            {"name": "Categoria", "description": "Categoria a la que pertenece"},
            {"name": "Director o participante", "description": "Dependiendo de su participación si fue director o participante"},
            {"name": "Coordinador o participante", "description": "Dependiendo de su participación si fue coordinador o participante"},
            {"name": "Otorgado por 1", "description": "Otorgado por ciencia y tecnología"},
            {"name": "Otorgado por 2", "description": "Otorgado por tecnologia e innovación"},
            {"name": "Maestria ", "description": "Obtención del grado de Maestro"},
            {"name": "Doctorado", "description": "Obtención del grado de Doctor"},
            {"name": "Nombramiento 1", "description": "Si fue nombrado secretario general o secretario de área"},
            {"name": "Nombramiento 2", "description": "Si fue nombrado en dirección de coordinación o área del IPN"},
            {"name": "Nombramiento 3", "description": "Si fue nombrado como director de centro de investigación de escuela superior o media superior"},
            {"name": "Nombramiento 4", "description": "Si fue nombrado como jefe de sección de posgrado o investigación"},
            {"name": "Nombramiento 5", "description": "Si fue nombrado como subdirector de escuela o centro de investigación o equivalente en el área central"},
            {"name": "Nombramiento 6", "description": "Si fue nombrado como coordinador de un programa de posgrado registrado en el PNPC"},
            {"name": "Nombramiento 7", "description": "Si fue nombrado como coordinador de un programa de posgrado no registrado en el PNPC"},
            {"name": "Nombramiento 8", "description": "Si fue nombrado en jefatura de departamento académico o administrativo en escuela o centro de investigación"},
            {"name": "Nombramiento 9", "description": "Si fue nombrado en jefatura de departamento académico o administrativo del IPN o equivalente en el área central"},
            {"name": "Nombramiento 10", "description": "Si fue nombrado presidente de academia"},
            {"name": "CONACYT", "description": "Depende si pertenece al CONACYT si no entonces se divide entre los participantes"},
            {"name": "Folio", "description": "Comprobar que el folio del documento sea el correcto"},
            {"name": "Excluir 4", "description": "Se excluye III.9"},
            {"name": "Asistencia", "description": "Comprobar la asistencia sin contraer compromisos laborales"},
            {"name": "Nivel educativo", "description": "Comprobar que el nivel educativo este correcto en el oficio ya que de esto dependera la cantidad de puntos"},
            {"name": "Tipo de premio", "description": " Diploma o constancia oficial que especifique el tipo de premio"},
            {"name": "Articulos externos", "description": "Para articulos externos (comite academico)"},
        ]

        # Usa un bucle para crear cada objeto Verificacion
        for verificacion_data in verificaciones:
            Verificacion.objects.create(**verificacion_data)


    dependencies = [
        ('Beca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('description', models.CharField(db_column='Description', max_length=255)),
            ],
            options={
                'db_table': 'Verification',
            },
        ),
        migrations.CreateModel(
            name='ActividadVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividadBeca', models.ForeignKey(db_column='ActivityID', on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones', to='Beca.actividadbeca')),
                ('verificacion', models.ForeignKey(db_column='VerificationID', on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='Beca.verificacion')),
            ],
            options={
                'db_table': 'ActivityVerification',
            },
        ),
         migrations.RunPython(cargar_datos),
    ]
